version: "2"
run:
  concurrency: 16
  go: "1.24"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  enable:
    - bidichk
    - copyloopvar
    - depguard
    - dupl
    - durationcheck
    - err113
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godox
    - gomoddirectives
    - gosec
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - usetesting
    - iface
    - intrange
    - perfsprint
    - recvcheck
  settings:
    copyloopvar:
      check-alias: false
    depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
      ignore-enum-members: ""
      package-scope-only: false
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: false
      min: 3
      max: 3
      ignore-calls: true
    gocritic:
      enabled-checks:
        - nestingReduce
        - ruleguard
        - truncateCmp
      disabled-checks:
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        underef:
          skipRecvDeref: true
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    gomoddirectives:
      replace-allow-list:
        - launchpad.net/gocheck
      replace-local: false
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gosec:
      includes:
        - G401
        - G306
        - G101
      excludes:
        - G204
      severity: low
      confidence: low
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)example
          per_char_threshold: "3.0"
          truncate: "32"
        G306: "0600"
    govet:
      disable:
        - nilness
        - unusedwrite
        - fieldalignment
        - shadow
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 12
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      ignore:
        - min
        - max
      qualified-name: false
    promlinter:
      strict: false
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: atomic
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: context-as-argument
        - name: defer
        - name: duplicated-imports
        - name: early-return
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: indent-error-flow
        - name: import-shadowing
        - name: range
        - name: range-val-in-closure
        - name: receiver-naming
        - name: string-format
        - name: struct-tag
        - name: superfluous-else
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: useless-break
        - name: waitgroup-by-value
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1001'
        - '-ST1003'
        - '-ST1016'
        - '-ST1020'
        - '-ST1021'
        - '-ST1022'
        - '-QF1008'
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
      dot-import-whitelist:
        - gopkg.in/telebot.v3
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    usetesting:
      context-background: true
      context-todo: true
      os-chdir: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: false
      os-create-temp: true
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      ignore-names:
        - err
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
      ignore-chan-recv-ok: false
      ignore-decls:
        - c echo.Context
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignore-sig-regexps:
        - \.New.*Error\(
      ignore-package-globs:
        - encoding/*
        - github.com/pkg/*
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: true
severity:
  default: error
formatters:
  settings:
    gofumpt:
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
