name: Test

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:

  setup_env:
    name: "Setup Env"
    step:

      - name: "Setup Go 1.15"
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: "Get dependences"
        run: make get

  test:
    name: "Test"
    needs: [ setup_env ]
    step:

      - name: "Run Test"

