name: Build And Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:

  lint:
    name: Lint
    uses: CSUSTers/csust-got/.github/workflows/lint.yml@dev


  test:
    name: Test
    uses: CSUSTers/csust-got/.github/workflows/test.yml@dev


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Get source
        uses: actions/checkout@v3

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: csust/csust-got-hoo
          tags: |
            latest-${{ github.ref_name }}
          containerfiles: |
            ./Dockerfile

      - name: Push To harbor
        id: push-to-harbor 
        uses: CSUSTers/push-to-registry@main
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWD }}
          retry: 1000
          
      - name: Restart Kubernetes Deployment
        id: restart-pod
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then NAME="csust-got"; elif [ "${{ github.ref }}" == "refs/heads/master" ]; then NAME="csust-got-prod"; fi; curl -X PUT -H "Content-Type: application/yaml" -H "Cookie: ${{ secrets.KubeCookie}}" -d '{"kind":"deployments","namespace":"csust","name":"'"$NAME"'"}' "${{ secrets.KubeURL}}"
