name: Build And Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:

  lint:
    name: Lint
    uses: CSUSTers/csust-got/.github/workflows/lint.yml@selfhost


  test:
    name: Test
    uses: CSUSTers/csust-got/.github/workflows/test.yml@selfhost


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Get source
        uses: actions/checkout@v2

      - name: Print version
        id: "version"
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          tags: |
            csust/csust-got:latest-${{ github.ref_name }}
          build-args: |
            TAG=${{ steps.version.outputs.sha }}
            BRANCH=${{ github.ref_name }}


  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ test, build ]
    if: github.ref_name == 'dev'
    steps:

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          port: ${{ secrets.PORT_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.PRIVATE_KEY_DEV }}
          script: cd csust-got-dev && docker-compose pull && docker-compose up -d --force-recreate
