name: Release

on:
  release:
    types:
      - published

jobs:
  lint:
    name: Lint
    uses: CSUSTers/csust-got/.github/workflows/lint.yml@master

  test:
    name: Test
    uses: CSUSTers/csust-got/.github/workflows/test.yml@master

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Sanitize tag name for Docker tag
        id: sanitize
        run: |
          # Replace / with - in tag name to make it valid for Docker tags
          SANITIZED_TAG=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "tag_name=$SANITIZED_TAG" >> $GITHUB_OUTPUT

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: csusters/csust-got
          tags: |
            latest
            ${{ steps.sanitize.outputs.tag_name }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            TAG=${{ steps.sanitize.outputs.tag_name }}
            BRANCH=release
          layers: true

      - name: Push To harbor
        id: push-to-harbor
        uses: CSUSTers/push-to-registry@main
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          retry: 1000
