name: Release

on:
  release:
    types:
      - published

jobs:
  lint:
    name: Lint
    uses: CSUSTers/csust-got/.github/workflows/lint.yml@master

  test:
    name: Test
    uses: CSUSTers/csust-got/.github/workflows/test.yml@master

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: csust/csust-got-hoo
          tags: |
            latest
            latest-${{ github.ref_name }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            TAG=${{ github.ref_name }}
            BRANCH=release
          layers: true

      - name: Push To harbor
        id: push-to-harbor
        uses: CSUSTers/push-to-registry@main
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWD }}
          retry: 1000
